var GroupHoldr;
(function(g){var h=function(){function e(a){if("undefined"===typeof a)throw Error("No settings object given to GroupHoldr.");if("undefined"===typeof a.groupNames)throw Error("No groupNames given to GroupHoldr.");if("undefined"===typeof a.groupTypes)throw Error("No groupTypes given to GroupHoldr.");this.functions={setGroup:{},getGroup:{},set:{},get:{},add:{},"delete":{}};this.setGroupNames(a.groupNames,a.groupTypes)}e.prototype.getFunctions=function(){return this.functions};e.prototype.getGroups=function(){return this.groups};
e.prototype.getGroup=function(a){return this.groups[a]};e.prototype.getGroupNames=function(){return this.groupNames};e.prototype.switchMemberGroup=function(a,b,c,d,e){if(this.groups[b].constructor===Array)this.functions["delete"][b](a,d);else this.functions["delete"][b](d);this.functions.add[c](a,e)};e.prototype.applyAll=function(a,b,c){void 0===c&&(c=void 0);var d;c?c.unshift(void 0):c=[void 0];a||(a=this);for(d=this.groupNames.length-1;0<=d;--d)c[0]=this.groups[this.groupNames[d]],b.apply(a,c);
c.shift()};e.prototype.applyOnAll=function(a,b,c){void 0===c&&(c=void 0);var d,e,f;c?c.unshift(void 0):c=[void 0];a||(a=this);for(e=this.groupNames.length-1;0<=e;--e)if(d=this.groups[this.groupNames[e]],d instanceof Array)for(f=0;f<d.length;f+=1)c[0]=d[f],b.apply(a,c);else for(f in d)d.hasOwnProperty(f)&&(c[0]=d[f],b.apply(a,c))};e.prototype.callAll=function(a,b){var c=Array.prototype.slice.call(arguments,1),d;a||(a=this);for(d=this.groupNames.length-1;0<=d;--d)c[0]=this.groups[this.groupNames[d]],
b.apply(a,c)};e.prototype.callOnAll=function(a,b){var c=Array.prototype.slice.call(arguments,1),d,e,f;a||(a=this);for(e=this.groupNames.length-1;0<=e;--e)if(d=this.groups[this.groupNames[e]],d instanceof Array)for(f=0;f<d.length;f+=1)c[0]=d[f],b.apply(a,c);else for(f in d)d.hasOwnProperty(f)&&(c[0]=d[f],b.apply(a,c))};e.prototype.clearArrays=function(){var a,b;for(b=this.groupNames.length-1;0<=b;--b)a=this.groups[this.groupNames[b]],a instanceof Array&&(a.length=0)};e.prototype.setGroupNames=function(a,
b){var c=this,d,e;this.groupNames&&this.clearFunctions();this.groupNames=a;this.groupTypes={};this.groupTypeNames={};b.constructor===Object?this.groupNames.forEach(function(a){c.groupTypes[a]=c.getTypeFunction(b[a]);c.groupTypeNames[a]=c.getTypeName(b[a])}):(d=this.getTypeFunction(b),e=this.getTypeName(b),this.groupNames.forEach(function(a){c.groupTypes[a]=d;c.groupTypeNames[a]=e}));this.setGroups();this.createFunctions()};e.prototype.clearFunctions=function(){this.groupNames.forEach(function(a){delete this["set"+
a+"Group"];delete this["get"+a+"Group"];delete this["set"+a];delete this["get"+a];delete this["add"+a];delete this["delete"+a];this.functions.setGroup={};this.functions.getGroup={};this.functions.set={};this.functions.get={};this.functions.add={};this.functions["delete"]={}})};e.prototype.setGroups=function(){var a=this;this.groups={};this.groupNames.forEach(function(b){a.groups[b]=new a.groupTypes[b]})};e.prototype.createFunctions=function(){var a,b;for(b=0;b<this.groupNames.length;b+=1)a=this.groupNames[b],
this.createFunctionSetGroup(a),this.createFunctionGetGroup(a),this.createFunctionSet(a),this.createFunctionGet(a),this.createFunctionAdd(a),this.createFunctionDelete(a)};e.prototype.createFunctionSetGroup=function(a){var b=this;this.functions.setGroup[a]=this["set"+a+"Group"]=function(c){b.groups[a]=c}};e.prototype.createFunctionGetGroup=function(a){var b=this;this.functions.getGroup[a]=this["get"+a+"Group"]=function(){return b.groups[a]}};e.prototype.createFunctionSet=function(a){this.functions.set[a]=
this["set"+a]=function(b,c){void 0===c&&(c=void 0);this.groups[a][b]=c}};e.prototype.createFunctionGet=function(a){this.functions.get[a]=this["get"+a]=function(b){return this.groups[a][b]}};e.prototype.createFunctionAdd=function(a){var b=this.groups[a];this.functions.add[a]=this.groupTypes[a]===Object?this["add"+a]=function(a,d){b[d]=a}:this["add"+a]=function(a,d){void 0!==d?b[d]=a:b.push(a)}};e.prototype.createFunctionDelete=function(a){var b=this.groups[a];this.functions["delete"][a]=this.groupTypes[a]===
Object?this["delete"+a]=function(a){delete b[a]}:this["delete"+a]=function(a,d){void 0===d&&(d=b.indexOf(a));-1!==d&&b.splice(d,1)}};e.prototype.getTypeName=function(a){return a&&a.charAt&&"o"===a.charAt(0).toLowerCase()?"Object":"Array"};e.prototype.getTypeFunction=function(a){return a&&a.charAt&&"o"===a.charAt(0).toLowerCase()?Object:Array};return e}();g.GroupHoldr=h})(GroupHoldr||(GroupHoldr={}));