var MapsCreatr;(function(k){var l=function(){return function(c,a,b){this.thing=c;this.title=c.title;this.reference=a;this.spawned=!1;this.left=a.x||0;this.top=a.y||0;this.right=this.left+(a.width||b.getFullPropertiesOf(this.title).width);this.bottom=this.top+(a.height||b.getFullPropertiesOf(this.title).height);a.position&&(this.position=a.position)}}();k.PreThing=l})(MapsCreatr||(MapsCreatr={}));
(function(k){var l=function(){function c(a){if(!a)throw Error("No settings object given to MapsCreatr.");if(!a.ObjectMaker)throw Error("No ObjectMakr given to MapsCreatr.");if("undefined"===typeof a.ObjectMaker.getFullProperties())throw Error("MapsCreatr's ObjectMaker must store full properties.");if(!a.groupTypes)throw Error("No groupTypes given to MapsCreatr.");this.ObjectMaker=a.ObjectMaker;this.groupTypes=a.groupTypes;this.keyGroupType=a.keyGroupType||"groupType";this.keyEntrance=a.keyEntrance||
"entrance";this.macros=a.macros||{};this.scope=a.scope||this;this.entrances=a.entrances;this.requireEntrance=a.requireEntrance;this.mapsRaw={};this.maps={};a.maps&&this.storeMaps(a.maps)}c.prototype.getObjectMaker=function(){return this.ObjectMaker};c.prototype.getGroupTypes=function(){return this.groupTypes};c.prototype.getKeyGroupType=function(){return this.keyGroupType};c.prototype.getKeyEntrance=function(){return this.keyEntrance};c.prototype.getMacros=function(){return this.macros};c.prototype.getScope=
function(){return this.scope};c.prototype.getRequireEntrance=function(){return this.requireEntrance};c.prototype.getMapsRaw=function(){return this.mapsRaw};c.prototype.getMaps=function(){return this.maps};c.prototype.getMapRaw=function(a){var b=this.mapsRaw[a];if(!b)throw Error("No map found under: "+a);return b};c.prototype.getMap=function(a){var b=this.maps[a];if(!b)throw Error("No map found under: "+a);b.initialized||this.initializeMap(b);return b};c.prototype.storeMaps=function(a){for(var b in a)a.hasOwnProperty(b)&&
this.storeMap(b,a[b])};c.prototype.storeMap=function(a,b){if(!a)throw Error("Maps cannot be created with no name.");var e=this.ObjectMaker.make("Map",b);this.mapsRaw[a]=b;if(!e.areas)throw Error("Maps cannot be used with no areas: "+a);if(!e.locations)throw Error("Maps cannot be used with no locations: "+a);return this.maps[a]=e};c.prototype.getPreThings=function(a){var b=a.map,e=a.creation,f=this.createObjectFromStringArray(this.groupTypes),d;a.collections={};for(d=0;d<e.length;d+=1)this.analyzePreSwitch(e[d],
f,a,b);return this.processPreThingsArrays(f)};c.prototype.analyzePreSwitch=function(a,b,e,f){return a.macro?this.analyzePreMacro(a,b,e,f):this.analyzePreThing(a,b,e,f)};c.prototype.analyzePreMacro=function(a,b,e,f){var d=this.macros[a.macro];if(!d)throw Error("A non-existent macro is referenced: '"+a.macro+"'.");if(a=d(a,b,e,f,this.scope))if(a instanceof Array)for(d=0;d<a.length;d+=1)this.analyzePreSwitch(a[d],b,e,f);else this.analyzePreSwitch(a,b,e,f);return a};c.prototype.analyzePreThing=function(a,
b,e,f){var d=a.thing,c,g;if(!this.ObjectMaker.hasFunction(d))throw Error("A non-existent Thing type is referenced: '"+d+"'.");g=new k.PreThing(this.ObjectMaker.make(d,a),a,this.ObjectMaker);c=g.thing;if(!g.thing[this.keyGroupType])throw Error("A Thing of type '"+d+"' does not contain a "+this.keyGroupType+".");if(-1===this.groupTypes.indexOf(g.thing[this.keyGroupType]))throw Error("A Thing of type '"+d+"' contains an unknown "+this.keyGroupType+".");b[g.thing[this.keyGroupType]].push(g);!c.noBoundaryStretch&&
e.boundaries&&this.stretchAreaBoundaries(g,e);void 0!==c[this.keyEntrance]&&"object"!==typeof c[this.keyEntrance]&&"undefined"!==typeof f.locations[c[this.keyEntrance]]&&("undefined"===typeof f.locations[c[this.keyEntrance]].xloc&&(f.locations[c[this.keyEntrance]].xloc=g.left),"undefined"===typeof f.locations[c[this.keyEntrance]].yloc&&(f.locations[c[this.keyEntrance]].yloc=g.top),f.locations[c[this.keyEntrance]].entrance=g.thing);a.collectionName&&e.collections&&this.ensureThingCollection(c,a.collectionName,
a.collectionKey,e);return g};c.prototype.initializeMap=function(a){this.setMapAreas(a);this.setMapLocations(a);a.initialized=!0};c.prototype.setMapAreas=function(a){var b=a.areas,e=a.locations,c=new b.constructor,d=new e.constructor,h,g;for(g in b)b.hasOwnProperty(g)&&(h=this.ObjectMaker.make("Area",b[g]),c[g]=h,h.map=a,h.name=g,h.boundaries={top:0,right:0,bottom:0,left:0});for(g in e)if(e.hasOwnProperty(g)){b=this.ObjectMaker.make("Location",e[g]);d[g]=b;b.entryRaw=e[g].entry;b.name=g;b.area=e[g].area||
0;if(this.requireEntrance&&!this.entrances.hasOwnProperty(b.entryRaw))throw Error("Location "+g+" has unknown entry string: "+b.entryRaw);this.entrances&&b.entryRaw?b.entry=this.entrances[b.entryRaw]:b.entry&&b.entry.constructor===String&&(b.entry=this.entrances[String(b.entry)])}a.areas=c;a.locations=d};c.prototype.setMapLocations=function(a){var b=a.locations,e=new b.constructor,c,d;for(d in b)if(b.hasOwnProperty(d)&&(c=this.ObjectMaker.make("Location",b[d]),e[d]=c,c.area=a.areas[b[d].area||0],
!e[d].area))throw Error("Location "+d+" references an invalid area:"+b[d].area);a.locations=e};c.prototype.stretchAreaBoundaries=function(a,b){var e=b.boundaries;e.top=Math.min(a.top,e.top);e.right=Math.max(a.right,e.right);e.bottom=Math.max(a.bottom,e.bottom);e.left=Math.min(a.left,e.left)};c.prototype.ensureThingCollection=function(a,b,e,c){var d=c.collections[b];d||(d=c.collections[b]={});a.collection=d;d[e]=a};c.prototype.processPreThingsArrays=function(a){var b=this,c={},f;for(f in a)if(a.hasOwnProperty(f)){var d=
a[f],h={xInc:this.getArraySorted(d,this.sortPreThingsXInc),xDec:this.getArraySorted(d,this.sortPreThingsXDec),yInc:this.getArraySorted(d,this.sortPreThingsYInc),yDec:this.getArraySorted(d,this.sortPreThingsYDec),push:function(a){b.addArraySorted(h.xInc,a,b.sortPreThingsXInc);b.addArraySorted(h.xDec,a,b.sortPreThingsXDec);b.addArraySorted(h.yInc,a,b.sortPreThingsYInc);b.addArraySorted(h.yDec,a,b.sortPreThingsYDec)}};c[f]=h}return c};c.prototype.createObjectFromStringArray=function(a){var b={},c;for(c=
0;c<a.length;c+=1)b[a[c]]=[];return b};c.prototype.getArraySorted=function(a,b){var c=a.slice();c.sort(b);return c};c.prototype.addArraySorted=function(a,b,c){for(var f=0,d=a.length,h;f!==d;)h=(f+d)/2|0,0>c(b,a[h])?d=h:f=h+1;f===d&&a.splice(f,0,b)};c.prototype.sortPreThingsXInc=function(a,b){return a.left===b.left?a.top-b.top:a.left-b.left};c.prototype.sortPreThingsXDec=function(a,b){return b.right===a.right?b.bottom-a.bottom:b.right-a.right};c.prototype.sortPreThingsYInc=function(a,b){return a.top===
b.top?a.left-b.left:a.top-b.top};c.prototype.sortPreThingsYDec=function(a,b){return b.bottom===a.bottom?b.right-a.right:b.bottom-a.bottom};return c}();k.MapsCreatr=l})(MapsCreatr||(MapsCreatr={}));