var PixelRendr;(function(k){var m=function(){return function(f,a){var d=a.source[2];this.sprites=f;this.direction=a.source[1];if("vertical"===this.direction||"corners"===this.direction)this.topheight=d.topheight|0,this.bottomheight=d.bottomheight|0;if("horizontal"===this.direction||"corners"===this.direction)this.rightwidth=d.rightwidth|0,this.leftwidth=d.leftwidth|0;this.middleStretch=d.middleStretch||!1}}();k.SpriteMultiple=m})(PixelRendr||(PixelRendr={}));
(function(k){var m=function(){return function(f,a){this.source=f;this.filter=a;this.sprites={};this.containers=[]}}();k.Render=m})(PixelRendr||(PixelRendr={}));
(function(k){var m=function(){function f(a){if(!a)throw Error("No settings given to PixelRendr.");if(!a.paletteDefault)throw Error("No paletteDefault given to PixelRendr.");this.paletteDefault=a.paletteDefault;this.digitsizeDefault=this.getDigitSizeFromArray(this.paletteDefault);this.digitsplit=new RegExp(".{1,"+this.digitsizeDefault+"}","g");this.library={raws:a.library||{}};this.scale=a.scale||1;this.filters=a.filters||{};this.flipVert=a.flipVert||"flip-vert";this.flipHoriz=a.flipHoriz||"flip-horiz";
this.spriteWidth=a.spriteWidth||"spriteWidth";this.spriteHeight=a.spriteHeight||"spriteHeight";this.Uint8ClampedArray=a.Uint8ClampedArray||window.Uint8ClampedArray||window.Uint8Array;this.ProcessorBase=new ChangeLinr.ChangeLinr({transforms:{spriteUnravel:this.spriteUnravel.bind(this),spriteApplyFilter:this.spriteApplyFilter.bind(this),spriteExpand:this.spriteExpand.bind(this),spriteGetArray:this.spriteGetArray.bind(this)},pipeline:["spriteUnravel","spriteApplyFilter","spriteExpand","spriteGetArray"]});
this.ProcessorDims=new ChangeLinr.ChangeLinr({transforms:{spriteRepeatRows:this.spriteRepeatRows.bind(this),spriteFlipDimensions:this.spriteFlipDimensions.bind(this)},pipeline:["spriteRepeatRows","spriteFlipDimensions"]});this.ProcessorEncode=new ChangeLinr.ChangeLinr({transforms:{imageGetData:this.imageGetData.bind(this),imageGetPixels:this.imageGetPixels.bind(this),imageMapPalette:this.imageMapPalette.bind(this),imageCombinePixels:this.imageCombinePixels.bind(this)},pipeline:["imageGetData","imageGetPixels",
"imageMapPalette","imageCombinePixels"],doUseCache:!1});this.library.sprites=this.libraryParse(this.library.raws);this.BaseFiler=new StringFilr.StringFilr({library:this.library.sprites,normal:"normal"});this.commandGenerators={multiple:this.generateSpriteCommandMultipleFromRender.bind(this),same:this.generateSpriteCommandSameFromRender.bind(this),filter:this.generateSpriteCommandFilterFromRender.bind(this)}}f.prototype.getBaseLibrary=function(){return this.BaseFiler.getLibrary()};f.prototype.getBaseFiler=
function(){return this.BaseFiler};f.prototype.getProcessorBase=function(){return this.ProcessorBase};f.prototype.getProcessorDims=function(){return this.ProcessorDims};f.prototype.getProcessorEncode=function(){return this.ProcessorEncode};f.prototype.getSpriteBase=function(a){return this.BaseFiler.get(a)};f.prototype.decode=function(a,d){var c=this.BaseFiler.get(a);if(!c)throw Error("No sprite found for "+a+".");c.sprites.hasOwnProperty(a)||this.generateRenderSprite(c,a,d);c=c.sprites[a];if(!c||c.constructor===
this.Uint8ClampedArray&&0===c.length)throw Error("Could not generate sprite for "+a+".");return c};f.prototype.encode=function(a,d){for(var c=[],b=2;b<arguments.length;b++)c[b-2]=arguments[b];b=this.ProcessorEncode.process(a);d&&d.apply(void 0,[b,a].concat(c));return b};f.prototype.encodeUri=function(a,d){var c=document.createElement("img");c.onload=this.encode.bind(this,c,d);c.src=a};f.prototype.generatePaletteFromRawData=function(a,d,c){var b={},h=[],g=[],e;for(e=0;e<a.length;e+=4)0===a[e+3]?d=
!0:b[a[e]]&&b[a[e]][a[e+1]]&&b[a[e]][a[e+1]][a[e+2]]&&b[a[e]][a[e+1]][a[e+2]][a[e+3]]||(b[a[e]]||(b[a[e]]={}),b[a[e]][a[e+1]]||(b[a[e]][a[e+1]]={}),b[a[e]][a[e+1]][a[e+2]]||(b[a[e]][a[e+1]][a[e+2]]={}),b[a[e]][a[e+1]][a[e+2]][a[e+3]]||(b[a[e]][a[e+1]][a[e+2]][a[e+3]]=!0,a[e]===a[e+1]&&a[e+1]===a[e+2]?g.push(a.subarray(e,e+4)):h.push(a.subarray(e,e+4))));g.sort(function(a,b){return a[0]-b[0]});h.sort(function(a,b){for(e=0;4>e;e+=1)if(a[e]!==b[e])return b[e]-a[e]});a=d?[new this.Uint8ClampedArray([0,
0,0,0])].concat(g).concat(h):g.concat(h);if(!c)return a;for(e=0;e<a.length;e+=1)a[e]=Array.prototype.slice.call(a[e]);return a};f.prototype.memcpyU8=function(a,d,c,b,h){void 0===c&&(c=0);void 0===b&&(b=0);void 0===h&&(h=Math.max(0,Math.min(a.length,d.length)));h+=0;b+=0;for(c+=0;h--;)d[b++]=a[c++]};f.prototype.libraryParse=function(a){var d={},c,b;for(b in a)if(a.hasOwnProperty(b)){c=a[b];switch(c.constructor){case String:d[b]=new k.Render(c);break;case Array:d[b]=new k.Render(c,c[1]);break;default:d[b]=
this.libraryParse(c)}d[b].constructor===k.Render&&d[b].containers.push({container:d,key:b})}return d};f.prototype.generateRenderSprite=function(a,d,c){c=a.source.constructor===String?this.generateSpriteSingleFromRender(a,d,c):this.commandGenerators[a.source[0]](a,d,c);a.sprites[d]=c};f.prototype.generateSpriteSingleFromRender=function(a,d,c){a=this.ProcessorBase.process(a.source,d,a.filter);return this.ProcessorDims.process(a,d,c)};f.prototype.generateSpriteCommandMultipleFromRender=function(a,d,
c){var b=a.source[2],h={},g,e,f=new k.SpriteMultiple(h,a),l;for(l in b)b.hasOwnProperty(l)&&(e=d+" "+l,g=this.ProcessorBase.process(b[l],e,a.filter),h[l]=this.ProcessorDims.process(g,e,c));return f};f.prototype.generateSpriteCommandSameFromRender=function(a,d,c){var b=this.followPath(this.library.sprites,a.source[1],0);this.replaceRenderInContainers(a,b);this.BaseFiler.clearCached(d);return this.decode(d,c)};f.prototype.generateSpriteCommandFilterFromRender=function(a,d,c){var b=this.filters[a.source[2]],
h=this.followPath(this.library.sprites,a.source[1],0);b||console.warn("Invalid filter provided: "+a.source[2]);h.constructor===k.Render?(b=new k.Render(h.source,{filter:b}),this.generateRenderSprite(b,d,c)):b=this.generateRendersFromFilter(h,b);this.replaceRenderInContainers(a,b);if(b.constructor===k.Render)return b.sprites[d];this.BaseFiler.clearCached(d);return this.decode(d,c)};f.prototype.generateRendersFromFilter=function(a,d){var c={},b,h;for(h in a)a.hasOwnProperty(h)&&(b=a[h],c[h]=b.constructor===
k.Render?new k.Render(b.source,{filter:d}):this.generateRendersFromFilter(b,d));return c};f.prototype.replaceRenderInContainers=function(a,d){var c,b;for(b=0;b<a.containers.length;b+=1)c=a.containers[b],c.container[c.key]=d,d.constructor===k.Render&&d.containers.push(c)};f.prototype.spriteUnravel=function(a){var d=this.getPaletteReferenceStarting(this.paletteDefault),c=this.digitsizeDefault,b=a.length,h,g,e,f="";for(g=0;g<b;)switch(a[g]){case "x":e=a.indexOf(",",++g);h=this.makeDigit(d[a.slice(g,
g+=c)],this.digitsizeDefault);for(g=Number(a.slice(g,e));g--;)f+=h;g=e+1;break;case "p":"["===a[++g]?(e=a.indexOf("]"),d=this.getPaletteReference(a.slice(g+1,e).split(",")),g=e+1,c=this.getDigitSizeFromObject(d)):(d=this.getPaletteReference(this.paletteDefault),c=this.digitsizeDefault);break;default:f+=this.makeDigit(d[a.slice(g,g+=c)],this.digitsizeDefault)}return f};f.prototype.spriteExpand=function(a){for(var d="",c=a.length,b=0,h,g;b<c;)for(g=a.slice(b,b+=this.digitsizeDefault),h=0;h<this.scale;++h)d+=
g;return d};f.prototype.spriteApplyFilter=function(a,d,c){if(!c||!c.filter)return a;d=c.filter;c=d[0];if(!c)return a;switch(c){case "palette":a=a.match(this.digitsplit);for(var b in d[1])d[1].hasOwnProperty(b)&&this.arrayReplace(a,b,d[1][b]);return a.join("");default:console.warn("Unknown filter: '"+c+"'.")}return a};f.prototype.spriteGetArray=function(a){var d=a.length/this.digitsizeDefault;a=a.match(this.digitsplit);var c=new this.Uint8ClampedArray(4*d),b,h,g,e;for(g=h=0;h<d;++h){b=this.paletteDefault[Number(a[h])];
for(e=0;4>e;++e)c[g+e]=b[e];g+=4}return c};f.prototype.spriteRepeatRows=function(a,d,c){d=new this.Uint8ClampedArray(a.length*this.scale);var b=4*c[this.spriteWidth];c=c[this.spriteHeight]/this.scale;var h=0,g=0,e,f;for(e=0;e<c;++e){for(f=0;f<this.scale;++f)this.memcpyU8(a,d,h,g,b),g+=b;h+=b}return d};f.prototype.spriteFlipDimensions=function(a,d,c){return-1!==d.indexOf(this.flipHoriz)?-1!==d.indexOf(this.flipVert)?this.flipSpriteArrayBoth(a):this.flipSpriteArrayHoriz(a,c):-1!==d.indexOf(this.flipVert)?
this.flipSpriteArrayVert(a,c):a};f.prototype.flipSpriteArrayHoriz=function(a,d){var c=a.length+0,b=d[this.spriteWidth]+0,h=new this.Uint8ClampedArray(c),b=4*b,g,e,f,l,k;for(f=0;f<c;f+=b)for(g=f,e=f+b-4,l=0;l<b;l+=4){for(k=0;4>k;++k)h[g+k]=a[e+k];g+=4;e-=4}return h};f.prototype.flipSpriteArrayVert=function(a,d){for(var c=a.length,b=d[this.spriteWidth]+0,f=new this.Uint8ClampedArray(c),b=4*b,g=0,e=c-b,k,l;g<c;){for(k=0;k<b;k+=4)for(l=0;4>l;++l)f[g+k+l]=a[e+k+l];g+=b;e-=b}return f};f.prototype.flipSpriteArrayBoth=
function(a){for(var d=a.length,c=new this.Uint8ClampedArray(d),b=a.length-4,f=0,g;f<d;){for(g=0;4>g;++g)c[f+g]=a[b+g];f+=4;b-=4}return c};f.prototype.imageGetData=function(a){var d=document.createElement("canvas"),c=d.getContext("2d");d.width=a.width;d.height=a.height;c.drawImage(a,0,0);return c.getImageData(0,0,a.width,a.height).data};f.prototype.imageGetPixels=function(a){var d=Array(a.length/4),c={},b,f,g;for(g=f=0;f<a.length;f+=4,g+=1)b=this.getClosestInPalette(this.paletteDefault,a.subarray(f,
f+4)),d[g]=b,c.hasOwnProperty(b)?c[b]+=1:c[b]=1;return[d,c]};f.prototype.imageMapPalette=function(a){var d=a[0];a=Object.keys(a[1]);var c=this.getDigitSizeFromArray(a),b=this.getValueIndices(a),d=d.map(function(a){return b[a]});return[a,d,c]};f.prototype.imageCombinePixels=function(a){var d=a[1],c=a[2],b=Math.max(3,Math.round(4/c)),f,g,e=0,k;for(a="p["+a[0].map(this.makeSizedDigit.bind(this,c)).join(",")+"]";e<d.length;){k=e+1;f=d[e];for(g=this.makeDigit(f,c);f===d[k];)k+=1;if(k-e>b)a+="x"+g+String(k-
e)+",",e=k;else{do a+=g,e+=1;while(e<k)}}return a};f.prototype.getDigitSizeFromArray=function(a){var d=0;for(a=a.length;1<=a;a/=10)d+=1;return d};f.prototype.getDigitSizeFromObject=function(a){return this.getDigitSizeFromArray(Object.keys(a))};f.prototype.getPaletteReference=function(a){var d={},c=this.getDigitSizeFromArray(a),b;for(b=0;b<a.length;b+=1)d[this.makeDigit(b,c)]=this.makeDigit(a[b],c);return d};f.prototype.getPaletteReferenceStarting=function(a){var d={},c,b;for(b=0;b<a.length;b+=1)c=
this.makeDigit(b,this.digitsizeDefault),d[c]=c;return d};f.prototype.getClosestInPalette=function(a,d){var c=Infinity,b,f,g;for(g=a.length-1;0<=g;--g)b=this.arrayDifference(a[g],d),b<c&&(c=b,f=g);return f};f.prototype.stringOf=function(a,d){return 0===d?"":Array(1+(d||1)).join(a)};f.prototype.makeDigit=function(a,d,c){void 0===c&&(c="0");return this.stringOf(c,Math.max(0,d-String(a).length))+a};f.prototype.makeSizedDigit=function(a,d){return this.makeDigit(d,a,"0")};f.prototype.arrayReplace=function(a,
d,c){for(var b=0;b<a.length;b+=1)a[b]===d&&(a[b]=c);return a};f.prototype.arrayDifference=function(a,d){var c=0,b;for(b=a.length-1;0<=b;--b)c+=Math.abs(a[b]-d[b])|0;return c};f.prototype.getValueIndices=function(a){var d={},c;for(c=0;c<a.length;c+=1)d[a[c]]=c;return d};f.prototype.followPath=function(a,d,c){return c<d.length&&a.hasOwnProperty(d[c])?this.followPath(a[d[c]],d,c+1):a};return f}();k.PixelRendr=m})(PixelRendr||(PixelRendr={}));